### ISSUE TITLE
The provided logo is different from the app logo

### ISSUE THREAD

**Issue by alrra** [operasoftware/logo#13]
There is a difference between the logo(s) provided in this repository and the Opera app logo:

| [Opera full red logo](https://operasoftware.github.io/logo/dest/logo/full-red.svg) | Opera app logo (OS X) | Difference between the two logos [1] | Animated gif to show the difference |
| :-: | :-: | :-: | :-: |
| <img src="https://cloud.githubusercontent.com/assets/1223565/12173239/4b54a09c-b55e-11e5-8d63-97fead79e523.png"> | <img src="https://cloud.githubusercontent.com/assets/1223565/12173237/4b50a8fc-b55e-11e5-9c9e-8821c1c37180.png"> | <img src="https://cloud.githubusercontent.com/assets/1223565/12173236/4b4f7f04-b55e-11e5-9c5f-b9d3327f8fe5.png"> | <img src="https://cloud.githubusercontent.com/assets/1223565/12173238/4b52f1d4-b55e-11e5-95d8-f91d9c3b3f0e.gif"> |

Is this intentional? 
## 

[1] The diff image was generated using ImageMagick's  [compare command line tool](http://www.imagemagick.org/script/compare.php):

``` sh
compare full_red_logo.png app_logo.png -compose src -highlight-color hotpink diff.png
```

**Comment by alrra** [comment]
Friendly ping @pepelsbey. :wave: 

(Cc: @mathiasbynens)

**Comment by pepelsbey** [comment]
Provided logos are rather Opera (company) logos than Opera (browser) ones. Each project create logo on its own, based on this. We could ask each team to provide the latest and the most accurate version and PR it to browser-logos project.

**Comment by alrra** [comment]
> Provided logos are rather Opera (company) logos than Opera (browser) ones. Each project create logo on its own, based on this.

@pepelsbey Thanks for the explanation!

> We could ask each team to provide the latest and the most accurate version and PR it to browser-logos project.

@pepelsbey That would be great!
